name: ci

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please enter your github name'
        required: true
      email:
        description: 'Please enter your github email'
        required: true
      version:
        description: 'Please enter your release version'
        required: true

jobs:

  readyGo:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          registry-url: https://registry.npmjs.org/
          
      - name: before scripts
        run: |
          echo "Current user.name: ${{ github.event.inputs.name }}"
          echo "Current user.email: ${{ github.event.inputs.email }}"
      
      - name: set git config
        run: |
          git config --global user.email ${{ github.event.inputs.email }}
          git config --global user.name ${{ github.event.inputs.name }}
          
      - name: install package
        run: |
          npm ci

      - name: lint code
        run: |
          npm run lint

      - name: build production dist
        run: |
          npm run prod
